# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_of_measurement', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.Probe')),
            ],
        ),
    ]
