# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20180115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='degrees',
            field=models.FloatField(),
        ),
    ]
